### ISSUE TITLE
Could not find a part of the path DaeTestAutomationPluginAutomationTestFrameworkCommands.cpp.obj.response

### ISSUE THREAD

**Issue by volvicTM** [npruehs/ue4-rts#118]
Hello,

I am attempting to load the example project from file: ue4-rts-1.0.0 (https://github.com/npruehs/ue4-rts/archive/1.0.0.zip).

After I extract the folder, I go to ue4-rts-1.0.0 -> Source -> RTSProject -> Doubleclick RTSProject.uproject or Rightclick RTSProject.uproject -> generate vs code, then Doubleclick RTSProject.uproject but they result in the same error:

```
2>UnrealBuildTool : error : Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Development\Resources\Unreal\ue4-rts\ue4-rts-1.0.0\Source\RTSProject\Plugins\DaedalicTestAutomationPlugin\Intermediate\Build\Win64\UE4Editor\Development\DaedalicTestAutomationPluginEditor\DaeTestAutomationPluginAutomationTestFrameworkCommands.cpp.obj.response'.
2>                           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>                           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>                           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>                           at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
2>                           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
2>                           at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
2>                           at UnrealBuildTool.Utils.WriteFileIfChanged(FileReference Location, String Contents, StringComparison Comparison) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\Utils.cs:line 1284
2>                           at UnrealBuildTool.TargetMakefile.CreateIntermediateTextFile(FileReference Location, String Contents) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\TargetMakefile.cs:line 687
2>                           at UnrealBuildTool.VCToolChain.CompileCPPFiles(CppCompileEnvironment CompileEnvironment, List`1 InputFiles, DirectoryReference OutputDir, String ModuleName, IActionGraphBuilder Graph) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Platform\Windows\VCToolChain.cs:line 1182
2>                           at UnrealBuildTool.UEBuildModuleCPP.Compile(ReadOnlyTargetRules Target, UEToolChain ToolChain, CppCompileEnvironment BinaryCompileEnvironment, FileReference SingleFileToCompile, ISourceFileWorkingSet WorkingSet, IActionGraphBuilder Graph) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModuleCPP.cs:line 420
2>                           at UnrealBuildTool.UEBuildBinary.SetupBinaryLinkEnvironment(ReadOnlyTargetRules Target, UEToolChain ToolChain, LinkEnvironment LinkEnvironment, CppCompileEnvironment CompileEnvironment, FileReference SingleFileToCompile, ISourceFileWorkingSet WorkingSet, DirectoryReference ExeDir, IActionGraphBuilder Graph) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildBinary.cs:line 717
2>                           at UnrealBuildTool.UEBuildBinary.Build(ReadOnlyTargetRules Target, UEToolChain ToolChain, CppCompileEnvironment CompileEnvironment, LinkEnvironment LinkEnvironment, FileReference SingleFileToCompile, ISourceFileWorkingSet WorkingSet, DirectoryReference ExeDir, IActionGraphBuilder Graph) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildBinary.cs:line 186
2>                           at UnrealBuildTool.UEBuildTarget.Build(BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, Boolean bIsAssemblingBuild, FileReference SingleFileToCompile) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1788
2>                           at UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 504
2>                           at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 247
2>                           at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 219
2>                           at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 550
```

This is the same result ofr both 4.24 and 4.25 and both new and existing projects.

I downloaded the Dedalic Plugin, and set it up according to their github page, in a existing project and that seems to also not be building for me, also missing a file.

**Comment by npruehs** [comment]
That's an odd one.

Can you provide more details, such as full build logs and/or a ZIP of your whole folder (without binaries)?

**Comment by volvicTM** [comment]
It appears to be due to a long location path, if I put it here:

`D:\Development\Resources\Unreal\ue4-rts-1.0.0\ue4-rts-1.0.0\Source\RTSProject`
it results in the above error.

If I put it here:

`C:\Users\Main\Desktop\RTSProject`
It builds and runs just fine.
The file that was missing in the original issue, now appears after building.

My bad!
